### ISSUE TITLE
[Suggestion] Daisy chain power cables support

### ISSUE THREAD

**Issue by mkfink** [Algalish/SmartIssueTracker#100]
If the buildings being placed are the daisy chain-able version from the [Daisy Chain Power Cables mod](https://ficsit.app/mod/4gKkJ9gvEVZDeu), build a power cable between each successive building when placing with Smart.

**Comment by Algalish** [comment]
@mkfink 

YES, I was thinking about the same idea and will do it very soon. As they say : "great minds think alike"
The other thing like that that I plan to do is when doing auto-connect to multiple buildigns - to copyrecepie for all of them from the first one. That will save even more time. Just need to remember to set the recepie to the first building before doing splitters with auto-connect

**Comment by Algalish** [comment]
For now it is not possible to do, will come back to that later this year
