### ISSUE TITLE
"Connect to building" feature: option to have non-forced P offset to accomodate for gap between buildings

### ISSUE THREAD

**Issue by Unreal-2K7** [Algalish/SmartIssueTracker#102]
Using version Smart!-0.15.0-first-test-for-patrons.smod
This is something that maybe not many people do, so it's low priority, i just wanted to give a heads up on this behaviour.

I like to lay constructors with a two step gap between them as to not have compenetrating robot arms during animations.
When using the "connect to building" feature, the max P offset value i can get is 400, which would be fine if the constructors where right up against eachother, but if there is a gap inbetween it forces it and i cannot increase it to align the splitter/merger with the constructors.

![immagine](https://user-images.githubusercontent.com/5400622/105626962-e5ff7800-5e33-11eb-8f82-be457b45b6d3.png)

Maybe a possibility is to have an option for not forcing the P parameter to accomodate for this case?

In any case, thanks a lot for the mod! It's super useful and it really feels like part of the base game handling!

**Comment by Algalish** [comment]
@Unreal-2K7  

Ok, I had an idea recently that forcing Spcaing(P) and Ofsset (T) (for second level of buildings)  should not be always forced.
Instead - it should be enforced only the first time that the building is found for auto-connect.
After that - you can change both P and T and if you connect to another building type - it will not be enforced. To get it back - you need to restart the hologram building process.
Do you think this is a good idea ?
Or just have an option in settings to turn the whole thing off completely?

Another great idea would be to detect the space between buildings automatically and not assume that they are near each other. But that sounds like too much work for now so maybe in the future.

**Comment by Unreal-2K7** [comment]
I belive that your first idea to just enforce it once at the beginning is the easier to implement and to use at runtime, so you won't need to add yet another option. Most of the times building will be just laid one after the other without gap, so no need to add algorithms to detect the offset, that's too much work that probably will rarely be useful.

Thank you for the effort!

**Comment by Algalish** [comment]
@Unreal-2K7  Done in V.15. Should be able to select a new mode in settings
