### ISSUE TITLE
feature request - different belt speeds splitter/splitter and splitter/building

### ISSUE THREAD

**Issue by catonthekbd** [Algalish/SmartIssueTracker#103]
I was wondering is it would be an idea for "auto" speed to be maximum belt speed between the chained splitters, and minimum speed between splitters and buildings?

**Comment by Algalish** [comment]
@catonthekbd  for it to be dividing the items to many buildings and not just to the first/second one?

That sounds itneresting. How a thing like that could be controlled - a separate config in settings - like  "level for conenction to buildings":  "auto "  "auto-1" "auto-2" and normal 1 2 3 4 5 ?

**Comment by catonthekbd** [comment]
I leave it to you, I initially thought about having seperate controls, but then thought UI could end up too complicated for the user :)

**Comment by catonthekbd** [comment]
Other random thought - if the splitters are on 3rd level up or higher (per screenshot on other bug), should you drop lifts rather than belts?

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
