### ISSUE TITLE
[Feature request] Add support for Conveyor Wall Mount

### ISSUE THREAD

**Issue by Greedo-fr** [Algalish/SmartIssueTracker#104]
Yes, we can make a big factory with this...
(also, it would be nice to have a P with an effect on vertical spacing...)

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
