### ISSUE TITLE
Lifts do not work if I use the Splitter/Mergers created by SMART

### ISSUE THREAD

**Issue by Tropelage** [Algalish/SmartIssueTracker#105]
Hello,
Excellent mod you have created.  I have an issue every time I use the mod to create multiple Splitters/Mergers and then use a lift to connect them to a building such as a Constructor or an Assembler.  If you can see from the pic I have attached, the Splitters in this case are distributing items to each other, but not down to the lifts.
![Liftissue](https://user-images.githubusercontent.com/71179003/105860417-8af88d00-5fbb-11eb-8e63-945c8bddabed.jpg)

**Comment by Algalish** [comment]
@Tropelage  Can you check this with the latest version of Smart! V.16 ? I fixed a lot of bug there including this one. Please reopen the issue if this is still not working for you
