### ISSUE TITLE
[Feature Request] Industrial Solutions compatibility

### ISSUE THREAD

**Issue by kevanaustin** [Algalish/SmartIssueTracker#106]
I like the parts available in 'Structural Solutions' Mod by Mike Skinner, any chance of getting SMART to work with them?

![image](https://user-images.githubusercontent.com/72109200/105929161-19900b80-609b-11eb-9798-3b98ca00b191.png)

**Comment by dempsey001** [comment]
up vote on this! great asset mod but after using SMART! it's almost painful when laying foundations. I'd love to see support added as well.

**Comment by Algalish** [comment]
@kevanaustin 
@dempsey001 
Hey guys, here is a test version with Structural Solutions mod support.
Let me know if there are any problems that I missed.

https://we.tl/t-rFoSztzWLo

**Comment by kevanaustin** [comment]
So far so good I thought there was a problem with collisions (Encroaching Others Clearance) but the Structural Solutions mod has none.

**Comment by dempsey001** [comment]
Hey folks, I played around with this a bit this morning. I'll try to do a bit more testing later but most of the foundations seem to work as expected. 

I found that if I try placing any size wall though (didn't matter if it was concrete or a glass bit) the game would crash immediately. I'm not sure if this may be a version issue because I had just picked up SS mod 0.0.6 today.

**Comment by Algalish** [comment]
@kevanaustin @dempsey001 
So the funny story is that Mike Skinner (the SS mod creator) had crashes all over the place when he was testing it.
And haven't had a single crash.
This is very weird and I can't find a reason for it yet.
So will investiaget further.

And no, it does not matter if 0.0.5 or 0.0.6 version of SS is used.

**Comment by Algalish** [comment]
@dempsey001  
Since you also had crashes - can you make a screenshot of your Smart! settings window? Maybe that will help me understand the problem.

**Comment by dempsey001** [comment]
I'm pretty sure I've never adjusted any of the settings. They should be default. Screenshot is attached.

![Settings](https://user-images.githubusercontent.com/1706488/107127689-d47f8c80-6885-11eb-9468-9447fa961d3a.png)

**Comment by kevanaustin** [comment]
I had a crash it was a curved window in the concrete section onto basic 8x8 foundation blocks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Algalish** [comment]
@kevanaustin @dempsey001 
Please try this version. It should not contain any crashes on any items.
https://we.tl/t-vBGb3hD0ib

**Comment by dempsey001** [comment]
@Algalish  - i've put in about 3-4 ish hours playing normally in my world using SS with Smart! a fair amount with concrete, frames and steel objects. I've haven't seen any crashes. Looks good my man!

Great work!!

**Comment by Algalish** [comment]
@dempsey001  Happy to hear that everything worked fine!
Released this in V.16 so I am closing the issue
