### ISSUE TITLE
[Bug] "Connect To Buildings" incorrectly and immutably assumes minimum spacing between buildings

### ISSUE THREAD

**Issue by zdravi** [Algalish/SmartIssueTracker#107]
Repro:
1. Place 2+ production buildings with any >0 spacing between them (screenshots attached have examples of smelters and constructors).
2. Place 2+ splitters with the "Connect to Buildings" setting enabled.

Expected:
- Proper linking with the additional space taken into account, and/or the ability to manually change the distance between the splitters.

Actual:
- Splitters will be placed in positions that assume the buildings have 0 space between them and attempt to link to the buildings from those positions, generally alternately failing or attaching at odd angles. Additionally, attempting to use P to space the splitters out to the proper distance fails, generally just causing the splitter to flash red briefly and the "invalid aim location" error message to briefly display.

Workaround:
- Temporarily disabling automatic building attachments at least allows the splitters to be manually spaced again.

![smelter_spacing](https://user-images.githubusercontent.com/1660528/105944097-7c3fc380-6017-11eb-9c0d-3c83d50fe186.jpg)
![smelter_bad_linking](https://user-images.githubusercontent.com/1660528/105944104-7ea21d80-6017-11eb-9a1d-9015059dd4f0.jpg)

![constructor_spacing](https://user-images.githubusercontent.com/1660528/105944103-7d70f080-6017-11eb-99cd-7f572c1bbf40.jpg)
![constructor_bad_linking](https://user-images.githubusercontent.com/1660528/105944101-7cd85a00-6017-11eb-8623-68ee07720ac2.jpg)

**Comment by Algalish** [comment]
Hey @zdravi  

Currently, this is an expected behavior - it only works with 0 spacing between buildings.
You can, however use manual spacing, by setting "Once" or "Off" the "Auto set space/level/offset" switch for now.
Then, using P you align splitters manually.twitc

I can't promise you that I will fix it ASAP, but probably soon.

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
