### ISSUE TITLE
[Request] Covered Conveyor support?

### ISSUE THREAD

**Issue by Baghiel** [Algalish/SmartIssueTracker#108]
I use the Covered Conveyor mod, and would love to see the belt connections from this have the option to use the belts in the Covered mod. As it is, I have the belt connect turned off so that I don't have to delete and replace the belts.

I do understand if this is considered a low priority, but never hurts to ask.

**Comment by Algalish** [comment]
@Baghiel 
I will try to check it out tomorrow. I have a lot on my plate right now so if there is no answer from me in 2 days - please remind me about it ok?

About low priority : If something can be done within 15 minutes or so - that's fine for me. I think this is the one just like that - where I need to download the mod, look at its assets name and then add this type of convey-our to the list, let's see.

**Comment by Baghiel** [comment]
All good. As I said, I understand if it's a low priority. It's not it is stopping me using the mod. Platforms are so much easier to deal with using it. If it appears in the mod, sweet. If not, no big deal. I just continue belting manually, as I have done since the game was launched.

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
