### ISSUE TITLE
Make an option to disable 2+ level of auto-connects

### ISSUE THREAD

**Issue by Algalish** [Algalish/SmartIssueTracker#109]

**Comment by Swamp-Ig** [comment]
You can hold down shift and alt and move down the scroll wheel to move it back to one level if you want.

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
