### ISSUE TITLE
T-functionality seems broken in 0.15?

### ISSUE THREAD

**Issue by SwampFalc** [Algalish/SmartIssueTracker#111]
I distinctly remember a previous version allowing me to make a line of foundations, and then twirling the entire line into, for example, a perfect diagonal.

That no longer seems possible? Only the second foundation gets offset with respect to the first, and then the rest goes on in a straight line.

![image](https://user-images.githubusercontent.com/20422044/106382334-368c4d80-63bf-11eb-8c7e-0dbc908780ef.png)

**Comment by faustinobsd** [comment]
I have the same issue.

**Comment by Algalish** [comment]
fixed in 16.3.1
