### ISSUE TITLE
Bugs related to smart stackable conveyor poles (from 2020-02-05 patreon update)

### ISSUE THREAD

**Issue by mkfink** [Algalish/SmartIssueTracker#113]
https://i.imgur.com/mJ9PINO.jpeg
See above for a combination of some of the effects.

Using the T, E, and U keys plus mouse wheel have some unexpected behavior with the new smart conveyor poles.
T just move the entire stack side to side, except for the first pole which stays in place.
E moves the entire stack vertically, and also creates a duplicate conveyor pole at the cursor.
U causes the conveyor poles and belts to stagger themselves vertically. The conveyor belts stay linked together, which is pretty funny but broken.

Seems like T and E are possibly useful, but the effect of U doesn't seem like it belongs on conveyor poles. It might be neat if instead of staggering vertically, maybe U could cause each successive stack to rotate one tick per scroll, for making broad arcs?

**Comment by mkfink** [comment]
Oh, and using P lets you create otherwise impossibly long conveyor belts, but that's not really as serious of an issue since you can make plenty of other impossible things with this mod.

**Comment by mkfink** [comment]
Sorry for all the posts, found one other issue when placing poles 'backwards' with mouse-wheel down. Hard to put into words, but the belts end up offset and incorrectly connected to the poles/each other. I'm not sure how much of this is a graphical glitch vs functional. Here's a short recording of it: https://youtu.be/mlIqt6Hxw20

**Comment by mkfink** [comment]
Another issue I'm seeing in this version is if I use smart to place multiple mergers (either connected to buildings or not) in reverse (mousewheel down) I am unable to connect belts to any of the sides of the mergers that are in line with the belts. So I can't connect to the output, and if I delete one of the mergers and try to replace it manually, belts refuse to connect to the neighboring mergers.

**Comment by Algalish** [comment]
@mkfink  Thx for all the comments.I will definetly take a look at all the options but I never intended anyone to use T E and U with stackable poles. yet. maybe I will make somethinw about it including your idea to create a round circle.
I know that on a rocky terrain a straight line is not very usefull but I have no way to fix it yet. to it is mostly for building on foundations.

Can you elaborate on the last comment about the mergers not being able to connect? with a video, if possible. that would be very helpfull

**Comment by mkfink** [comment]
Sure, here's what I'm seeing with mergers placed in reverse (something similar also happens with splitters): https://youtu.be/amRC_iTdcXE

**Comment by Algalish** [comment]
@mkfink  I fixed the problem with splitters/mergers when you build them in reverse. both visually and logically. same for stackable poles. 
I also added a limit to the poles - they cannot be longer then the game's limit for belts.
And set the default spacing for poles to 20m. I think it is better this way.
Also added the correct way to use "U" for poles to build on ramps

Really hope I haven't broken any existing logic with it.

If you could check and confirm that this is now fixed - that would be awesome.

https://we.tl/t-BXz5p38J84

**Comment by mkfink** [comment]
Looking good! I don't see any issues placing things in reverse now. Tried hooking up to a few buildings and it seems to work fine.

The longer default belt pole spacing is good, and the limit seems to work with P. With U though, you can make impossibly long and steep vertical belts.

**Comment by Algalish** [comment]
@mkfink 
Great, so I will just fix the problems with U then.
Any ideas how to control that? Limit something : for example maximum Up level or Up level mult by the lenght and decrease lenght if it all becomes too big?
This is not as crytical bug as infinite spacing or reverse placement so maybe we think about it and fix in an update.

**Comment by mkfink** [comment]
Yeah, it's not really a major issue. Can you limit the length of the belt based on the cost? Cap that at 26 aluminum per belt and no matter how it's built that should limit the length at least.
