### ISSUE TITLE
Crash with Structural Solutions

### ISSUE THREAD

**Issue by mkfink** [Algalish/SmartIssueTracker#114]
With the version of Smart on Patreon with Structural Solutions support, my game crashes when I select certain objects from the build menu/hotbar. I haven't tested everything, but so far the crashes seem limited to flat wall type objects:
- Concrete Wall
- Concrete Wall 8m
- Rounded concrete wall
- Roll up door

Things that did not crash:
- I-beams
- Concrete blocks, chamfers, cylinders, domes, curved walls

Same results with Structural Solutions 0.0.5 and 0.0.6

**Comment by Algalish** [comment]
@mkfink 
Can you please try this version?
The crashes should be fixed here.
https://we.tl/t-vBGb3hD0ib

**Comment by mkfink** [comment]
Yep, that fixes the crash. Thanks!

Now just a few of the larger walls/doors have the wrong default spacing:
8x8 concrete wall /door wall, curved wall cap 8m (glass and concrete), 8x8 door - Vertical offset is 4 instead of 8
8x16 door - vertical offset is 4 instead of 8, horizontal offset is 8 instead of 16
16x16 door, 16x16 glass wall - vertical offset is 4 instead of 16, horizontal offset is 8 instead of 16

**Comment by Algalish** [comment]
@mkfink Released the V.16 with all the above things fixed. 
Thx for testing it!!

**Comment by mkfink** [comment]
Thanks for the update, most of that is fixed! :D
8x8 Concrete Wall and 8x8 Door Wall still have incorrect vertical offset. 8x8 conveyor wall is correct.
16x16 glass wall still has incorrect horizontal offset. Vertical offset is good. 16x16 door is all good.
