### ISSUE TITLE
Crash with 0.15.0

### ISSUE THREAD

**Issue by ArrionHammerson** [Algalish/SmartIssueTracker#115]
When I install 0.15.0 the game crashes on launch with "SML HAS CRASHED: Errors occurred during mod loading stage 'mod discovery'. Failed to load zip mod from .../SmartFoundations_0.15.0.smod (Failed to extract data objects) It works fine when I revert to 0.14.0. If it's a mod conflict I'm in trouble because I have around 28 installed and it'd be tough to isolate. I'm using SMM to install but I also tried it directly from Github with the same results.

**Comment by Algalish** [comment]
@ArrionHammerson 
No, there is no known mod confilicts that I know.
It looks like the file was damaged when download.
I can try to explain to you how to clean mod cache or ask to reinstall SML but I will post tonight a V.16 of Smart so it is better to wait for that and then test it. So let me know if it will still cause problems for you.

**Comment by ArrionHammerson** [comment]
I dug around in the SMM settings and found the command to clear the cache. That seems to have done the trick, thank you. It was a bit confusing that a manual install didn't fix the problem, but at least I have this in my toolbox for future problems now.

**Comment by Algalish** [comment]
@ArrionHammerson  Glad that you worked it out
