### ISSUE TITLE
[Bug] Multiplayer crashes with autoconnects (0.16)

### ISSUE THREAD

**Issue by camelpockets** [Algalish/SmartIssueTracker#118]
The autoconnect functionality with splitters into any building (constructors, assemblers, refineries) crashes any non-host player on in a multiplayer game with version 0.16. The error occurs immediately when a splitter "detects" one of the buildings and attempts to create a connection between the splitter and the building. Placing a splitter as normal is fine.

**Comment by Algalish** [comment]
@camelpockets 
got it, will take care of it

**Comment by LooSik** [comment]
Is it possible to get multiplayer functionality for auto-connect as well ? So far it only worked for host, in 0.16 (crashes client) / 0.15 (didn't connect but showed outlines).

**Comment by camelpockets** [comment]
In my game, the host seems to control the auto-connect functionality entirely, between toggling it on and off and changing the default belts

**Comment by Algalish** [comment]
@camelpockets @LooSik 
I am overrun by work this week, sorry.
Making MP work with auto-connect is very important and I will take care of it ASAP.

**Comment by LooSik** [comment]
Seems like @camelpockets is right. 
Enabling connection between mergers/splitters on host seem to make it work for clients too.
But clients have no option to disable it then ( it will place them regardless of client setting )

**Comment by Algalish** [comment]
16.3.1
crash is not going to happen on clients, its just not going to work, thats it
