### ISSUE TITLE
Auto Connect not working for Manufactures

### ISSUE THREAD

**Issue by CYRUS1469** [Algalish/SmartIssueTracker#120]
First off Love the mod cant live without it,    Onto the issue I've noticed  it will not auto connect to Manufactures  MK1 thru MK4  if this is fixable that would be a huge help.  Please and thank you .

**Comment by CYRUS1469** [comment]
for the input on a manufacture, i use staggered Splitters at the heights , than connect as such ground and 2nd lvl are belted, the 3rd and 4th are using conveyor lifts to connect, if this is also possible that be fantastic.    Also, note the Mergers on the output of Manufactures do not auto-connect at this time.

**Comment by CYRUS1469** [comment]
![Screenshot20210217-20594200000](https://user-images.githubusercontent.com/79235440/108294726-6d56b780-7164-11eb-94c4-e0acdf3e248b.png)

**Comment by StefanR23** [comment]
It would be really cool  to decide on Z height if someone wants to have one the ground floor.
Personally I like to have 2 level above the ground to walk underneath the belts. And then it has the same height as the machine itself

![image](https://user-images.githubusercontent.com/81093991/111908739-98ca0c00-8a5a-11eb-9f61-a668b05448be.png)

To have different directions on the level is not necessary. In these rare cases I can do the job manually.

**Comment by Algalish** [comment]
@CYRUS1469 @StefanR23 
I will look into that guys.

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
