### ISSUE TITLE
Conveyours are 2d instead of 3d for auto-connect for different levels

### ISSUE THREAD

**Issue by Algalish** [Algalish/SmartIssueTracker#126]
https://cdn.discordapp.com/attachments/777233974878797895/812614368091963421/unknown.png

**Comment by nbrugger-tgm** [comment]
This doesn't works for me at all. Autoconnect doesn't pay attention to height difference and the belt just goes verticaly

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
