### ISSUE TITLE
[Issue] Auto-connect work only in 2 of 3 positions

### ISSUE THREAD

**Issue by DarAmetis** [Algalish/SmartIssueTracker#128]
All on screenshots

![Screenshot_1](https://user-images.githubusercontent.com/76752782/110204636-24517380-7e85-11eb-833f-20192f29abc7.png)
![Screenshot_3](https://user-images.githubusercontent.com/76752782/110204637-2adfeb00-7e85-11eb-82de-f802cba8e1c3.png)
![Screenshot_4](https://user-images.githubusercontent.com/76752782/110204641-2fa49f00-7e85-11eb-8b59-3602a5f2db47.png)

**Comment by DarAmetis** [comment]
And this dont work too
![Screenshot_2](https://user-images.githubusercontent.com/76752782/110204718-9de96180-7e85-11eb-8eb7-3c2c378211db.png)

**Comment by Algalish** [comment]
@DarAmetis  never intended for it to work that way. but maybe in the future will handle it.
but for now - too much work writing all that conditions. the code is insanely complex as is.
unless a lot of people will ask for this

**Comment by StefanR23** [comment]
Title is misleading.
it's not "2 of 3"  . All 3 positions for a splitters are working.
Your request belongs to a merger. And mergers as an input for a series of factories makes no sense.

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
