### ISSUE TITLE
[Feature] Auto-connect for conveyors

### ISSUE THREAD

**Issue by DarAmetis** [Algalish/SmartIssueTracker#129]
I would also like to see the feature of automatic creation of pipelines between the nearest points of attachment. If that's even possible. 

![Screenshot_5](https://user-images.githubusercontent.com/76752782/110205174-dab65800-7e87-11eb-898d-37b658a0e600.png)

**Comment by Algalish** [comment]
yep, that is in progress

**Comment by Pedrat** [comment]
i was just wondering if this got any attention or is it dropped? thanks!

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
