### ISSUE TITLE
Stacking splitters or mergers provides the wrong belt connection

### ISSUE THREAD

**Issue by JDLanyon** [Algalish/SmartIssueTracker#130]
When stacking splitters and/or mergers, attempting to use multiple splitters/mergers with spacing results in the first belt being 1 lower than expected. (must have belts automatically connect)

[An unlisted 40 second video can be found here.](https://youtu.be/CacKWSxESME)

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
