### ISSUE TITLE
Please add support for "Painted Wall Foundation and Pipe" mod

### ISSUE THREAD

**Issue by SOLOnerves** [Algalish/SmartIssueTracker#132]
I love the "Smart!" mod and can't live without it, but it would be great if you added support for the "Painted Wall Foundation and Pipe" mod. here's a link to it "[https://ficsit.app/mod/87aJFK855U49Q6](https://ficsit.app/mod/87aJFK855U49Q6)".

**Comment by Algalish** [comment]
@SOLOnerves 
I will try to add the mod in the next updates, looks cool

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
