### ISSUE TITLE
Update 4 Compatibility

### ISSUE THREAD

**Issue by FaTaL6266** [Algalish/SmartIssueTracker#133]
With Update 4 coming out in the next few days, do you expect the smart mod to still be compatible with the new version of the game? Obviously, you won't know for certain until the release of the update, but just wondering if you have a general idea. If you believe it will need to be worked on before it is usable, how long do you think it would take to make it compatible? #

**Comment by Algalish** [comment]
This is mostly depending on how soon new header files and moding tools would be availible to us moders.
It usually takes a few hours to update the mod for new update once these tools are ready.
I don't know exactly how soon after the update those  tools would be available : but usually they are ready after 1-2 days of an update, like it happened with fluids update.
but there is also engine update of the game that was out in EXP and there are still no headers/modding tools ready for that.

Anyway, as soon as I know something I will post the info

**Comment by odoucet** [comment]
no header file available yet ?

**Comment by Algalish** [comment]
@odoucet  nope, no mod can work on update 4 yet

**Comment by kellertk** [comment]
@Algalish Looks like SML and SMM just released Update 4 compatibility. Looking forward to using Smart! again :)

**Comment by matthock** [comment]
Keep in mind that Smart! is relatively complex, so it may take a few days to upgrade. Still, it's great news, and thank you so much @Algalish for your hard work on it!

**Comment by Algalish** [comment]
@matthock Yep, and because game changed a lot - some thing may be broken and will require a fix.
Life is just crazy these days, don't have a lot of time. But I will dedicate this whole Friday for updating Smart! , so hold on guys.

**Comment by devotoare** [comment]
@Algalish Thanks for all your work!

**Comment by andyryan869** [comment]
@Algalish I understand you are working on smart mod today is that why it is not showing up in game yet even though SMM says it is compatible? can not wait for it it is really hard to play with out the smart mod when you start over takes for ever to place a few hundred foundations love your work and all the extra things you have added and that you are still adding in to it can't wait to see what future updates will have keep it up sir.

**Comment by FaTaL6266** [comment]
> @matthock Yep, and because game changed a lot - some thing may be broken and will require a fix.
> Life is just crazy these days, don't have a lot of time. But I will dedicate this whole Friday for updating Smart! , so hold on guys.

I'll just throw this out there, if you ever want help, I've been working on learning UE4 coding and designing and stuff and would be glad to learn how to create mods for a game like Satisfactory. Love your work and hope to see 'Smart!' up and running soon. It's hands down the best mod out there in my opinion.

**Comment by OspreyGozo** [comment]
Thanks for your dedication! Looking forward to the update to version 4. Once one has tasted Smart!, it is hard to go back to the old ways.

**Comment by Algalish** [comment]
![Screenshot_132](https://user-images.githubusercontent.com/1682176/115258384-9cc07b00-a139-11eb-9d37-96a7fa0bf598.png)
Soon™

**Comment by Merkury90** [comment]
Can't wait for new version. Not possible for me to play the game without this mod after I got used to all it's functions ;)

**Comment by OspreyGozo** [comment]
> 
> 
> Can't wait for new version. Not possible for me to play the game without this mod after I got used to all it's functions ;)
Same here!

**Comment by Algalish** [comment]
Thank you all for waiting
