### ISSUE TITLE
Auto connect to buildings suggestion.

### ISSUE THREAD

**Issue by Jumbo-storm** [Algalish/SmartIssueTracker#134]
I want that you are gonna update so, auto-connect to buildings is right.
(Before it sad with splitters and mergers. But now it says just: "Auto-connect to buildings".)
And it does not auto-connect to buildings.

For example:
Auto-connect from smelter to constructor, directly. (If you don't want splitters, between.)
Connect constructor to constructor. (Iron road to Screw, example. That needs constructor to constructor. If you do not want splitters, between.)

Video on my suggestion;
https://www.youtube.com/watch?v=LAMVK4ANyMM
(Maybe only Chrome users... Tip, Maybe...
If you don't want it to open in this tab/"window". You can right-click on the link and select: "Open link in new tab". Then it should open the YouTube video in a new tab/"window".)

**Comment by Algalish** [comment]
@Jumbo-storm 
I think I understand what you mean and it would be super cool to have something like that in game.
I honestly don't know how long it will take me but I like the idea and will look into that.

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
