### ISSUE TITLE
Upgrade all connected conveyors

### ISSUE THREAD

**Issue by sergeylamzin** [Algalish/SmartIssueTracker#135]
I love this mod. Super awesome!
I am planning on starting a new playthrough for U4 and one thign I find extremely annoying is having to upgrade all conveyor segments on your main bus throughout the game.
Any chance you could add a function to mass upgrade all conveyors/lifts that are connected through any number of splitters/mergers/lifts?

**Comment by Algalish** [comment]
@sergeylamzin I thought about it but haven't tried that yet. No plans for this right now but maybe in a month or two I will look into that and do something like that.

Maybe if you do an upgrade for one of the belts and the system scans for all connected belts and also upgrades them - that could be a good idea. But need to test if this is possible to implement

**Comment by Algalish** [comment]
This is a new feature.  New features are now in discord ( https://discord.gg/mUKAb9Br ) and only bugs are left here.
