### ISSUE TITLE
[Feature] Dismantle connected belt(s) when dismantling building

### ISSUE THREAD

**Issue by Temujin2887** [Algalish/SmartIssueTracker#137]
It would be really nice if there was an option to have dismantling a building also dismantle the belts connected to that building.

**Comment by Algalish** [comment]
@Temujin2887 
But it should be togglable, yes?
Like if you hold Shift - then they will be dismantled, and if not - then not?
What do you think is best?

**Comment by Temujin2887** [comment]
Can it be both a setting and a modifier key?
Dismantle connected belts (Default: False)
Dismantle+Shift inverts that bool
That way you can set your preference for what you do most of the time, and then use the modifier for a quick removal in the opposite mode?

If all that's too complicated, then just a Shift+Dismantle to delete connected is probably fine as long as it works with mass dismantle too.

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
