### ISSUE TITLE
[Feature] Auto-connect for storage (single/double)

### ISSUE THREAD

**Issue by Temujin2887** [Algalish/SmartIssueTracker#138]
It would be nice if mergers/splitters would auto connect to storage containers.
It would also be nice if when creating an grid of containers they auto-connect in a daisy chain for bulk storage.
3 x 4 storage daisy chain example:
X > X > X > X
X > X > X > X
X > X > X > X

**Comment by Algalish** [comment]
@Temujin2887 
Yep, I will definitely implement that.

**Comment by Algalish** [comment]
This is a new feature.  New features are now in discord ( https://discord.gg/mUKAb9Br ) and only bugs are left here.
