### ISSUE TITLE
[Feature] Smart Power Outlets/Poles

### ISSUE THREAD

**Issue by Temujin2887** [Algalish/SmartIssueTracker#139]
With the new hoverpack, I'm finding myself making lines/grids of ceiling power outlets and its super tedious. The exact thing Smart! is good at fixing! :P Can we get these added (with connecting lines) so we can quickly drop out spaced out ceiling power grids (or outside power pole grids/lines)

**Comment by Algalish** [comment]
I will try to add support soon.

But closing the ussue here since all new features are now in discord ( https://discord.gg/mUKAb9Br ) and only bugs are left here.
