### ISSUE TITLE
Ability to turn off smart connect with a hotkey.

### ISSUE THREAD

**Issue by Swamp-Ig** [Algalish/SmartIssueTracker#140]
Hi, I love auto-connect, but sometimes it doesn't do what I want.

It would be good if we could toggle auto-connect with a simple hot-key. Maybe default start with it on, but the hot key turns it off for one shot.

**Comment by Algalish** [comment]
@Swamp-Ig  yep, I will implement something like that

**Comment by azeroth2b** [comment]
Came here looking for this issue, was not disappointed.

**Comment by dcbishop** [comment]
I wonder if it would be possible to add it to the press 'R' to Default/Zoop/Vertical menu

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
