### ISSUE TITLE
Pressing LSHIFT doesn't work

### ISSUE THREAD

**Issue by HelpIamHavingProblem** [Algalish/SmartIssueTracker#141]
I'm pressing LSHIFT while I have the Foundation out and nothing's happening

**Comment by SiD-23RUS** [comment]
Smart still doesn't work on CL150216 (tried on Steam and Epic clients)

**Comment by Mattia9875** [comment]
Is there any plan to make it work? (Asking because of the low activity during the month)

**Comment by Algalish** [comment]
@Mattia9875  @HelpIamHavingProblem  @SiD-23RUS 
This is probably because the mod is not working for Update4 of the game.
I will update the mod for Update4 of the game on the 16 of April (Friday) to make it work.

**Comment by HelpIamHavingProblem** [comment]
Oh okay, thanks!

**Comment by SiD-23RUS** [comment]
> I will update the mod for Update4 of the game on the

Thank you very much! We all will wait for it! Awesome mod!
