### ISSUE TITLE
Update 4

### ISSUE THREAD

**Issue by orkide628** [Algalish/SmartIssueTracker#142]
Will you update smart mod and compatible with update 4 Satisfactory.If you will do, when you will. Thanks

**Comment by dalex4444** [comment]
Would Like that as well.

**Comment by javacupix** [comment]
Update planned on Friday https://github.com/Algalish/SmartIssueTracker/issues/141#issuecomment-819659628

**Comment by orkide628** [comment]
Oh, thank you so much! I missed issue 141
