### ISSUE TITLE
Unable to open selection wheel when any building that can be duplicated is selected

### ISSUE THREAD

**Issue by benipk** [Algalish/SmartIssueTracker#144]
Title.

**Comment by inwestygator** [comment]
I can confirm: seems like the mod overwrites the hotkey fonctionalities and does not bypass 'E' for the Quick Switch radial menu, wherever the mod gives the availability for mass assembly.

**Comment by matthock** [comment]
Being able to disable/change this key is by far my #1 needed updated. I have become even more addicted to the radial menu than to Smart! in the short time I've had it.

**Comment by Algalish** [comment]
Yes, this is a known bug and will be fixed very soon

**Comment by Algalish** [comment]
This is fixed in 16.3.1
Closing the issue
