### ISSUE TITLE
Blenders, Power Storage, and Power Switch don't appear to be supported

### ISSUE THREAD

**Issue by escidmore** [Algalish/SmartIssueTracker#146]
Steps to reproduce:

1) Start building a blender, power storage, or power switch
2) Hold shift and scroll to try to increase number of items built

Expected result: Smart will allow you to build multiple items in a line

Actual result: Smart does not appear to do anything; building rotates, as it would with the mouse wheel normally

**Comment by escidmore** [comment]
This appears to be true for the drone port and all lights as well.

May be true for particle accelerator, but I don't have it unlocked in my world currently.

**Comment by Algalish** [comment]
yep, those are new things that I haven't supported yet. but will be soon

**Comment by nbrugger-tgm** [comment]
Same goes for packagers

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
