### ISSUE TITLE
Plugin 'SmartFoundations' failed to load because module 'SmartFoundations' could not be found.

### ISSUE THREAD

**Issue by sloisel** [Algalish/SmartIssueTracker#148]
Hi.

I have the game on Steam, and I downloaded the mod manager from ficsit.app. From the mod manager, I installed "Smart" and launched "Satisfactory". I get a modal dialog box with the error message in the title of this post, and then "Satisfactory" exits.

At this point, I cannot use "Smart" at all.

**Comment by Algalish** [comment]
Hi! This is a very common problem and here are the solutions below
1) Please make sure your game is of the last version (it was updated  1 day ago)
2) Make sure that Satisfactory Mod Manager has the latest version. If it is - reinstall it again.

**Comment by inwestygator** [comment]
I had the same issue, mod manager reinstall was required.

**Comment by sloisel** [comment]
I don't know what I did, but it fixed itself. Thanks for the must-have mod!
