### ISSUE TITLE
CTD after placing Merger/Splitter @StorageContainer

### ISSUE THREAD

**Issue by litlleblackman** [Algalish/SmartIssueTracker#149]
Steps to reproduce:
1. Place Container
2. Place Merger/Splitter by holding Shift
3. CTD

CrashReport:

>Version: 151248, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Epic, NetMode: Listen Server, IsUsingMods: Yes
Assertion failed: Cast<AFGBuildableConveyorBase>( mSnappedConection->GetOwner() ) [File:D:/ws/SB-160502110050-fad/UE4/Games/FactoryGame/Source/FactoryGame/Private/Hologram/FGConveyorAttachmentHologram.cpp] [Line: 433] make sure we are only connecting to conveyors
UE4_Core_Win64_Shipping!AssertFailedImplV() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:100]
UE4_Core_Win64_Shipping!FDebug::CheckVerifyFailedImpl() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:450]
UE4_FactoryGame_Win64_Shipping!AFGConveyorAttachmentHologram::ConfigureComponents() [d:\ws\sb-160502110050-fad\ue4\games\factorygame\source\factorygame\private\hologram\fgconveyorattachmenthologram.cpp:433]
UE4_FactoryGame_Win64_Shipping!AFGBuildableHologram::Construct() [d:\ws\sb-160502110050-fad\ue4\games\factorygame\source\factorygame\private\hologram\fgbuildablehologram.cpp:390]
UE4_FactoryGame_Win64_Shipping!UFGBuildGunStateBuild::InternalConstructHologram() [d:\ws\sb-160502110050-fad\ue4\games\factorygame\source\factorygame\private\equipment\fgbuildgunbuild.cpp:1038]
UE4_FactoryGame_Win64_Shipping!UFGBuildGunStateBuild::Server_ConstructHologram_Implementation() [d:\ws\sb-160502110050-fad\ue4\games\factorygame\source\factorygame\private\equipment\fgbuildgunbuild.cpp:999]
UE4_FactoryGame_Win64_Shipping!UFGBuildGunStateBuild::execServer_ConstructHologram() [d:\ws\sb-160502110050-fad\ue4\games\factorygame\intermediate\build\win64\ue4\inc\factorygame\fgbuildgunbuild.gen.cpp:386]
UE4_CoreUObject_Win64_Shipping!UFunction::Invoke() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\class.cpp:5543]
UE4_CoreUObject_Win64_Shipping!UObject::ProcessEvent() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1916]
UE4_FactoryGame_Win64_Shipping!UFGBuildGunStateBuild::Server_ConstructHologram() [d:\ws\sb-160502110050-fad\ue4\games\factorygame\intermediate\build\win64\ue4\inc\factorygame\fgbuildgunbuild.gen.cpp:463]
UE4_FactoryGame_Win64_Shipping!UFGBuildGunStateBuild::InternalExecuteDuBuildStepInput() [d:\ws\sb-160502110050-fad\ue4\games\factorygame\source\factorygame\private\equipment\fgbuildgunbuild.cpp:486]
UE4_CoreUObject_Win64_Shipping!UFunction::Invoke() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\class.cpp:5543]
UE4_CoreUObject_Win64_Shipping!UObject::CallFunction() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:929]
UE4_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:997]
UE4_CoreUObject_Win64_Shipping!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:828]
UE4_CoreUObject_Win64_Shipping!UObject::execLocalFinalFunction() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:2923]
UE4_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:997]
UE4_CoreUObject_Win64_Shipping!UObject::ProcessInternal() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1087]
UE4_CoreUObject_Win64_Shipping!UFunction::Invoke() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\class.cpp:5543]
UE4_CoreUObject_Win64_Shipping!UObject::ProcessEvent() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1916]
UE4_Engine_Win64_Shipping!FInputActionUnifiedDelegate::Execute() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\classes\components\inputcomponent.h:306]
UE4_Engine_Win64_Shipping!UPlayerInput::ProcessInputStack() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\userinterface\playerinput.cpp:1325]
UE4_Engine_Win64_Shipping!APlayerController::ProcessPlayerInput() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\playercontroller.cpp:2570]
UE4_Engine_Win64_Shipping!APlayerController::TickPlayerInput() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\playercontroller.cpp:4580]
UE4_Engine_Win64_Shipping!APlayerController::PlayerTick() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\playercontroller.cpp:2228]
UE4_FactoryGame_Win64_Shipping!AFGPlayerController::PlayerTick() [d:\ws\sb-160502110050-fad\ue4\games\factorygame\source\factorygame\private\fgplayercontroller.cpp:262]
UE4_Engine_Win64_Shipping!APlayerController::TickActor() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\playercontroller.cpp:4726]
UE4_Engine_Win64_Shipping!FActorTickFunction::ExecuteTick() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\actor.cpp:174]
UE4_Engine_Win64_Shipping!FTickFunctionTask::DoTask() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\ticktaskmanager.cpp:288]
UE4_Engine_Win64_Shipping!TGraphTask<FTickFunctionTask>::ExecuteTask() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\public\async\taskgraphinterfaces.h:854]
UE4_Core_Win64_Shipping!FNamedTaskThread::ProcessTasksUntilQuit() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\private\async\taskgraph.cpp:586]
UE4_Core_Win64_Shipping!FTaskGraphImplementation::WaitUntilTasksComplete() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\private\async\taskgraph.cpp:1479]
UE4_Engine_Win64_Shipping!FTickTaskSequencer::ReleaseTickGroup() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\ticktaskmanager.cpp:562]
UE4_Engine_Win64_Shipping!FTickTaskManager::RunTickGroup() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\ticktaskmanager.cpp:1535]
UE4_Engine_Win64_Shipping!UWorld::Tick() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\leveltick.cpp:1558]
UE4_Engine_Win64_Shipping!UGameEngine::Tick() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\gameengine.cpp:1697]
UE4_FactoryGame_Win64_Shipping!UFGGameEngine::Tick() [d:\ws\sb-160502110050-fad\ue4\games\factorygame\source\factorygame\private\fggameengine.cpp:13]
UE4_Win64_Shipping!FEngineLoop::Tick() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\launch\private\launchengineloop.cpp:4910]
UE4_Win64_Shipping!GuardedMain() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\launch\private\launch.cpp:169]
UE4_Win64_Shipping!GuardedMainWrapper() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\launch\private\windows\launchwindows.cpp:137]
UE4_Win64_Shipping!WinMain() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\launch\private\windows\launchwindows.cpp:268]
UE4_Win64_Shipping!__scrt_common_main_seh() [d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

![2021-04-22 16_24_04-Window](https://user-images.githubusercontent.com/83021367/115732458-4dbc5500-a388-11eb-871f-e77e83636e07.png)

![2021-04-22 16_31_34-Window](https://user-images.githubusercontent.com/83021367/115732432-45641a00-a388-11eb-89f0-f2dffcc7bc4d.png)

**Comment by Algalish** [comment]
interesting crash. I will have a look

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
