### ISSUE TITLE
Starting rotation is kind of random and disturbing

### ISSUE THREAD

**Issue by Algalish** [Algalish/SmartIssueTracker#15]
Make rotation always point to the direction a player is looking.

**Comment by Rosuav** [comment]
The latest update has an arrow showing the direction. It's now a little more intrusive (you KNOW that you have the mod active), but I think it's a good thing. Helps to know which way shift and alt will work.

**Comment by Algalish** [comment]
@Rosuav  I think that apart from its primary function, knowing that the mod is active is a good thing. Yep, without this arrow you could spend extra time finding out where the foundation is pointing at.

**Comment by Rosuav** [comment]
Agreed. :+1:

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
