### ISSUE TITLE
The game does not start with the mod enabled

### ISSUE THREAD

**Issue by VituaT** [Algalish/SmartIssueTracker#150]
The game does not start with the mod enabled. When i start the game, it displays the following message
![IMG_1595](https://user-images.githubusercontent.com/83079762/115887261-6e54df80-a45a-11eb-950b-19390612c7ab.jpg)

**Comment by inwestygator** [comment]
For me mod and mod manager reinstall solved this issue.

**Comment by VituaT** [comment]
I tried game and manager reinstall

**Comment by Veldian78** [comment]
i had that then removed the mod closed launcher, restarted PC... then opened launcher and installed mod again and it fixed it

**Comment by Algalish** [comment]
@VituaT  you need to clear cache in SMM. Or create a new profile in SMM - that also helps

**Comment by Algalish** [comment]
oh god, I am so tired of this popular problem of SMM

**Comment by VituaT** [comment]
Clearing cache and creating new profile is not work.

**Comment by Algalish** [comment]
@VituaT  Are you starting the game from SMM or from Steam/Epic?
You need to run it from SMM

**Comment by VituaT** [comment]
From SMM

**Comment by Algalish** [comment]
All the people that experienced this are ok now. So you need to do it all once again - Re-install the SMM with the new launcher. create a new profile, without doing a copy of the old one (so it will be blank)- add some mods there and run the game. hope that helps

**Comment by VituaT** [comment]
I tried again, stil without effect.

**Comment by VituaT** [comment]
Game is working with MK++ mod. Some mods (for example Mini map, more milestones +100) also works.

**Comment by Algalish** [comment]
@VituaT  Please go to modding discord - this problem is explained there many times. People will be able to help you better then me
https://discord.gg/pq8As6qD
