### ISSUE TITLE
[Feature] X3-Roads

### ISSUE THREAD

**Issue by Veldian78** [Algalish/SmartIssueTracker#151]
When trying to use the X3-Roads with SMART to place more then 1 at a time using ALT and SHIFT it does not work i've uninstalled and reinstalled both mods thinking it might be a download issue but it still does not work.

**Comment by Algalish** [comment]
I urge you to read update descriptions before opening issues.
The current version does not have support for other mods because of the U4 update.
It will be back ASAP
