### ISSUE TITLE
启动器安装好MOD后，进游戏后没有MODS标识，进入存档也没有效果

### ISSUE THREAD

**Issue by HaoNanLin98** [Algalish/SmartIssueTracker#152]
![image](https://user-images.githubusercontent.com/83098551/115937236-fde5a700-a4c9-11eb-8083-5e82e80a7c89.png)
![184539BB5A84360520F2D4C10377B3AA](https://user-images.githubusercontent.com/83098551/115937286-2b325500-a4ca-11eb-9d2a-dd8f91656272.png)

**Comment by nbrugger-tgm** [comment]
This issue seems very unspecific can you may clarify the problem in English language?

**Comment by Algalish** [comment]
@HaoNanLin98  You are using SML version 2.2.1 and you need to install SML v3.
Just create a new Profile and install mods again

**Comment by Algalish** [comment]
@HaoNanLin98  this is a very popular problem, not related to the mod.
1) reinstall SMM from the new launcher from the website
2) remove your existing SMM profile and create an empty one
3) add mods to this new empty profile
4) launch the game from the SMM, not directly

and the problem should be gone
