### ISSUE TITLE
Belts flickering when using auto-connect

### ISSUE THREAD

**Issue by Gavenator** [Algalish/SmartIssueTracker#153]
When connecting splitters and mergers to buildings using auto-connect the hologram of the belts flicker.

Link to video of issue:
https://i.gyazo.com/6cff0dc11892fd59fd1b306fd79d57f2.mp4

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
