### ISSUE TITLE
Need key rebind support

### ISSUE THREAD

**Issue by UnknwnSoldier** [Algalish/SmartIssueTracker#154]
Can we please get the ability to change the keys used for SMART functions?  I use ESDF for movement so the E key interferes with my ability to move around while doing certain SMART tasks.

**Comment by Algalish** [comment]
I will try to move all the keys settings to the native game settings menu. but no ETA on that

**Comment by stanfear** [comment]
Hi !
I'd also love to have rebinding available (even if through a config file) 
I use OKLM (on an AZERTY keyboard) for movement, and not being able to move right when building is enough to make the mod unusable. (only pressing M when building to open menu is nice, and allows to move around even without the menu poping up, but it is not enough sadly)

please do something soon (like I said, config file is fine) as this mod really is something I'd like to use on a daily basis.

**Comment by benley** [comment]
Another request for key rebinding! I use a left-handed mouse, and IJKL for normal movement so L conflicts with this mod.

Is there currently a way of changing the keybindings by editing a config file on disk, or something like that?

**Comment by Algalish** [comment]
will try to make ALL the keys re-bindable in the next few weeks

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
