### ISSUE TITLE
Settings window confusing, missing a lot of labels and tooltips

### ISSUE THREAD

**Issue by arw82** [Algalish/SmartIssueTracker#156]
Not sure if this is intended. It's not at all clear what many checkboxes/pulldown boxes are for. 

![image](https://user-images.githubusercontent.com/20416661/115964323-1dd49500-a4e1-11eb-8cf3-991b44a186f3.png)

Game build 151248, Mod version 1.0.0

**Comment by Sebastiaanv2** [comment]
Experiencing the same issue

**Comment by Algalish** [comment]
@sctprog  @Sebastiaanv2 
As I said in the update notes - the settings screen is fracked up for now and settings are not saved. I will fix it as soon as I can.

**Comment by sctprog** [comment]
> @sctprog @Sebastiaanv2
> As I said in the update notes - the settings screen is fracked up for now and settings are not saved. I will fix it as soon as I can.

Missed that, thank you!

**Comment by Sebastiaanv2** [comment]
> > @sctprog @Sebastiaanv2
> > As I said in the update notes - the settings screen is fracked up for now and settings are not saved. I will fix it as soon as I can.
> 
> Missed that, thank you!

my bad aswell, seem to have missed that, thanks

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
