### ISSUE TITLE
Water Extractor snapping

### ISSUE THREAD

**Issue by Discobuble** [Algalish/SmartIssueTracker#159]
Seems the Smart! mod is disabling snapping on Water Extractors. Tried with all 3 mods I'm using, without, and just each induvially. And it only happends when Smart! is enabled. And I can't seem to see anything in the settings to change how CTRL interacts with the mod.

**Comment by Algalish** [comment]
Support for water extractors is removed from Smart! because there is normal snapping now

**Comment by masayoshi-louis** [comment]
please also remove the support for MK++ water extractors from Smart!
