### ISSUE TITLE
Autoconnect does not work on foundaries

### ISSUE THREAD

**Issue by JKamsker** [Algalish/SmartIssueTracker#160]
merging gives this: 
![image](https://user-images.githubusercontent.com/11245306/116452717-4f8d8900-a85e-11eb-98c4-83776368dac3.png)

Cannot adjust the distance. It's somehow an invalid fixed size

**Comment by Algalish** [comment]
auto-connect only works if the buildings are close to each other , without spaces.
at least for now it is how it works

**Comment by rado92** [comment]
wait....you can auto connect?

**Comment by Algalish** [comment]
@rado92  https://youtu.be/-HbCKSABeWE
and the next one

**Comment by rado92** [comment]
@Algalish amazing work man. you make this game so much better. I cant wait for your mod to work with smm 3.1.0
