### ISSUE TITLE
Unable to load SMART! MOD!!!

### ISSUE THREAD

**Issue by yinchuzhou** [Algalish/SmartIssueTracker#161]
![无标题](https://user-images.githubusercontent.com/40012444/116547766-e709df00-a925-11eb-86c8-798fe52428ba.png)
Is there a solution?

**Comment by yinchuzhou** [comment]
The module "smartfoundations" could not be found, so the plug-in "smartfoundations" failed to load.Make sure the plug-in is installed correctly, or consider disabling it in your project.

**Comment by Algalish** [comment]
@yinchuzhou  this is a very popular problem, not related to the mod.
1) reinstall SMM from the new launcher from the website
2) remove your existing SMM profile and create an empty one
3) add mods to this new empty profile
4) launch the game from the SMM, not directly

and the problem should be gone

**Comment by yinchuzhou** [comment]
The above methods have been tried, but the problem still can't be solved. Other mods can be used.

**Comment by sirsamon** [comment]
Hi There, i have the exact same error, i have tried above and a few different options

**Comment by Algalish** [comment]
Are you guys on experimental by any chance?

**Comment by sirsamon** [comment]
yes i am

**Comment by Algalish** [comment]
please switch to EearlyEccess instead of Experimental for now
