### ISSUE TITLE
Missing some plugin.

### ISSUE THREAD

**Issue by Marix54** [Algalish/SmartIssueTracker#164]
Hello,
after downloading Smart foundations mode, i can't start Satisfactory.

![Výstřižek](https://user-images.githubusercontent.com/83689865/117101750-32354f00-ad77-11eb-9643-1dd32972cfb8.PNG)

Do you now how to repair it?

**Comment by FaillordXD** [comment]
I had something similar i changed to an older version (16.0) and it works. 
Version 16.2.0 did not work for me. 

![Satisfactory 16_2](https://user-images.githubusercontent.com/83690972/117103385-91e12980-ad7a-11eb-9d5a-5b215dd4f016.PNG)

**Comment by Algalish** [comment]
@Marix54 @FaillordXD Are you guys by any chance on EXP version  of the game?
If yes - then please wait for an update

**Comment by FaillordXD** [comment]
Yes I am

**Comment by Marix54** [comment]
No, I'm on normal early access. I tried old mod version too, but with same result.

**Comment by Algalish** [comment]
make sure that SMM is updated and create a new profile for SMM and make sure to launch the game from SMM

**Comment by ivmakk** [comment]
@Marix54 for me helped downgrading SatisfactoryModManager to [v2.4.3](https://github.com/satisfactorymodding/SatisfactoryModManager/releases/tag/v2.4.3) (it's compatible with the Steam Early Access v 0.4.2.0).

**Comment by Marix54** [comment]
@ivmakk Thanks, it helped!

**Comment by sirsamon** [comment]
> @Marix54 for me helped downgrading SatisfactoryModManager to [v2.4.3](https://github.com/satisfactorymodding/SatisfactoryModManager/releases/tag/v2.4.3) (it's compatible with the Steam's Satisfactory Early Access v0.4.2.0). End the last version of the mod (16.2.0) works with it

I did this and all is working perfectly now, thanks very much
