### ISSUE TITLE
Left shift not recognized on macOS via steamlink

### ISSUE THREAD

**Issue by bandycj** [Algalish/SmartIssueTracker#165]
Smart does not recognize when left shift is pressed while building when playing on macOS 11.3 via steamlink to a windows 10 PC. The game does recognize left shift when binding keys in the game settings so it is correctly being relayed to the game.

I realize this is an edge case but I figured I'd file a bug incase it was a simple "look for additional key codes" kind of fix.

Thanks :)

**Comment by Algalish** [comment]
Sorry, but there is no way for me to test that. Maybe when I'll make the keys completey customazable - you could remap Shift.
I can try adding RightShift but that can break some other logic, so its probably better for you to wait for the key-remap or build with arrows
