### ISSUE TITLE
Refinery autoconnect input problem

### ISSUE THREAD

**Issue by kovila77** [Algalish/SmartIssueTracker#166]
When locate spliter closely to input of refinery (with autoconnect ON), the belt appeared inside refinery. This look like no belts.
![Снимок экрана 2021-05-08 041919](https://user-images.githubusercontent.com/46498109/117517371-49618000-afb5-11eb-9365-8ea2d3cb3410.png)

**Comment by d-hey** [comment]
Having the same issue. Also with other buildings when placing a splitter very close to the input.

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
