### ISSUE TITLE
Error while starting game

### ISSUE THREAD

**Issue by NKLzz** [Algalish/SmartIssueTracker#168]
Hi,

I get the followed error if I start Satifactory with the Smart! mod.
Other mods don´t cause any issues and are playable. 

SML version: 2.4.3
Satisfactory version: Early Access CL#151248
Used version Smart!: Latest

![Unbenannt](https://user-images.githubusercontent.com/83875091/117544241-d857b200-b020-11eb-9b8b-2dfd5f3df9a3.PNG)

Can I somehow fix this problem?

**Comment by Algalish** [comment]
@NKLzz  The latest version works only on EXP, not EA as stated in the description. This patch will soon hit EA and then Smart! will work on EA without update

**Comment by NKLzz** [comment]
Ok cool thanks! 
I do use steam tho. 

I´ll wait for the update :)
