### ISSUE TITLE
Power Storage Mk++ Support not working [Version 16.3.1]

### ISSUE THREAD

**Issue by niightly** [Algalish/SmartIssueTracker#169]
I saw in the recent version the support for mk++ power storage support was added, but SHIFT other commands do not work, it just rotates the building.

BTW, your mod is awesome, I think it should be added permanently on the game :D (and you hired as well)
Great thinking man.

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
