### ISSUE TITLE
Build configuration should be retained after placement

### ISSUE THREAD

**Issue by jboulter11** [Algalish/SmartIssueTracker#17]
I often want to place the same configuration multiple times and always have to dial in the size each time I place.

Would be easier if, after placing, the configuration didn't get cleared.

Use cases:
- Building a long path in chunks (like for a train track)
- Building a large floor for a factory in chunks

**Comment by Algalish** [comment]
@jboulter11  Yes, that is a good idea. Some button like “R”(restore) will restore the last used configuration. Or even up to ten last configurations that can be obtained by pressing R multiple times.

**Comment by Algalish** [comment]
This is done in 16.3 with the "R" button. For now it saves automatically the last configuration and restores by pressing "R"
