### ISSUE TITLE
Staking Conveyor Supports Don't All Connect

### ISSUE THREAD

**Issue by DovaChicken** [Algalish/SmartIssueTracker#170]
When using multiple of the auto connect smart conveyors all but the first and last of the conveyors can be connected to via another belt.

**To Reproduce**
1. Produce more than 1 line of auto connect belts
2. try and connect belts to any of the conveyor pole middle sections or most ends

 - Game Branch: [e.g. Early Access]
 - Game Type Epic,]
 - Game Version [e.g. CL151248] 
 - Mod Type [Public ]
 - Mod Version [e.g. 16..3.1 ]
 - SMM/SML Version [3.0 ]

**Additional context**

**Comment by Natsirt21** [comment]
I have the same one https://www.youtube.com/watch?v=SNrka0rja40

**Comment by Algalish** [comment]
This is fixed in 17.0.6
