### ISSUE TITLE
Bug convoyor belt stack big bug 

### ISSUE THREAD

**Issue by Natsirt21** [Algalish/SmartIssueTracker#171]
Video https://www.youtube.com/watch?v=SNrka0rja40

 - Game Branch: Early Access
 - Game Type Epic
 - Game Version CL151248
 - Mod Type Public
 - Mod Version 16.3.1             https://gyazo.com/bb2d2417675437e2cdf8b7dcb2a69d91
 - SMM/SML Version 3.0.0 ?   https://gyazo.com/d00b640413008ab37588857ba5cdf8d2

**Comment by Algalish** [comment]
Fixed in 17.0.6
@Natsirt21  I know it took too long but it is finally fixed!
