### ISSUE TITLE
water extractor doesn't work anymore

### ISSUE THREAD

**Issue by flixs123** [Algalish/SmartIssueTracker#174]
**Describe the bug**
water extractor doesn't work/copy anymore

**To Reproduce**

**Screenshot of the mod's configuration**
Please add a screenshot with the settings screen so that we could understand better what is going on.

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**(please complete the following information):**
 - Game Branch: [e.g. Early Access, Experimental]
 - Game Type [e.g. Epic, Steam]
 - Game Version [e.g. CL135567]
 - Mod Type [e.g. Public, Patreon ]
 - Mod Version [e.g. 16.1 ]
 - SMM/SML Version [e.g. 3.1 ]

**Additional context**

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
