### ISSUE TITLE
Not able to place Splitters in front of Fabrikator

### ISSUE THREAD

**Issue by Sowarie** [Algalish/SmartIssueTracker#175]
I play with a friend together (he is the Host), over all all goes fine but i cant place Splitter in front of the Fabrikator. He as the host get`s the normal from the mod generated models for the splitters but i dont get that and i cant even place them.

![Screenshot (5)](https://user-images.githubusercontent.com/84231768/118360273-2de31000-b587-11eb-91bf-bcfd3a1cb211.png)
![Screenshot (6)](https://user-images.githubusercontent.com/84231768/118360276-2facd380-b587-11eb-809c-24890b527020.png)
![Screenshot (7)](https://user-images.githubusercontent.com/84231768/118360279-30de0080-b587-11eb-8e1b-cb33106dc544.png)

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
