### ISSUE TITLE
Walls don't line up when zooped. They seem to be clipping slightly. Any fixes?

### ISSUE THREAD

**Issue by hippocratical** [Algalish/SmartIssueTracker#181]
[IMAGE](https://i.imgur.com/BZhxDke.jpg)
This only happens with walls.
Foundations work fine.
I've messed with the various settings and nothing fixes it.
Holding down P and adjusting offset just makes gaps between each wall piece.
Ideas?

**Comment by log136** [comment]
+1 this is happening to me too. quite annoying as building large walls is a great use for this mod.

**Comment by jdphenix** [comment]
Disabling "Soft Clipping for Everything" (another unrelated mod) fixed this for me.

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
