### ISSUE TITLE
Auto-connect can't handle symmetry

### ISSUE THREAD

**Issue by Krzeszny** [Algalish/SmartIssueTracker#183]
**Describe the bug**
With 2 outer lines of machines (smelters, constructors, etc) facing inwards into at least 2 lines of mergers, Smart! connects each Smelter to 2 Mergers at once.

**To Reproduce**
1. Place 2 smelters/constructors on the sides facing inwards, with enough space for 2 mergers on the inside
2. Use Smart! to place 2 mergers on the inside
3. Each machine now has 2 conveyor belts connected, one to each merger.

**Screenshot of the mod's configuration**
![FactoryGame-Win64-Shipping_98OVX6tmCl](https://user-images.githubusercontent.com/10529134/161436468-450bd34b-fb54-45d0-93d9-5779ac0bdcdd.png)

**Screenshots/videos**
Smelters:
![[FactoryGame-Win64-Shipping_ZHTuCY1IIL](https://user-images.githubusercontent.com/10529134/161436164-bded64c5-33cc-4a3b-a4c9-f1d](https://i.imgur.com/aVfngId.jpeg)
![FactoryGame-Win64-Shipping_Z2WJLcItBK](https://user-images.githubusercontent.com/10529134/161436166-8e2d1562-4e7a-4219-bfef-018a954132b1.jpg)
e434ffe94.jpg)
Constructors:
![FactoryGame-Win64-Shipping_q4bS6JRr1E](https://user-images.githubusercontent.com/10529134/161436560-8d86165c-9d07-4f68-9a35-f6c114623c5d.jpg)
![FactoryGame-Win64-Shipping_NgBQHdS1Ot](https://user-images.githubusercontent.com/10529134/161436571-50018f39-274a-49c7-882c-9789b4ec2b79.jpg)

**(please complete the following information):**
 - Game Branch: Early Access
 - Game Type Steam
 - Game Version CL177909
 - Mod Type Public
 - Mod Version 17.0.11
 - SMM/SML Version v2.8.1

**Additional context**
Most likely happens with all machines.

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
