### ISSUE TITLE
Misaligned conveyor belts between splitters/mergers

### ISSUE THREAD

**Issue by Krzeszny** [Algalish/SmartIssueTracker#184]
**Describe the bug**
For some reason, belts don't connect splitters or mergers properly in some situations such as this one. It doesn't matter if Auto-Connect to buildings is on or off.

**To Reproduce**
1. Place splitters and mergers like in the screenshots
2. Whether auto-connect is turned on or off, you should see the bug

**Screenshot of the mod's configuration**
![FactoryGame-Win64-Shipping_VLorKg6I89](https://user-images.githubusercontent.com/10529134/161530054-7ac2c097-6a8d-4ecc-8596-3e8dd4bd07ee.png)

**Screenshots/videos**
![UiDDePvbBz](https://user-images.githubusercontent.com/10529134/161529882-d028eafb-c513-4227-9569-6a6fc81c364d.jpg)
![FactoryGame-Win64-Shipping_iVsfhWDcL8](https://user-images.githubusercontent.com/10529134/161529889-c1e5b201-5dcd-449b-ba39-06ad198573df.jpg)

**(please complete the following information):**
- Game Branch: Early Access
- Game Type Steam
- Game Version CL177909
- Mod Type Public
- Mod Version 17.0.11
- SMM/SML Version v2.8.1

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
