### ISSUE TITLE
Ability to snap foundation to cardinal points

### ISSUE THREAD

**Issue by ngppgn** [Algalish/SmartIssueTracker#19]
For the more ocd/aesthetic-minded folks, it could be interesting to have the option for the foundations to be oriented exactly towards the cardinal points. Another mod has special foundation items just for that functionality, but it'd be nice if it was added to the regular foundations.

**Comment by Algalish** [comment]
@ngppgn  Can you give me the name of that mod so I could have a look?

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
