### ISSUE TITLE
Add support for MoarFactory walls and foundations

### ISSUE THREAD

**Issue by Algalish** [Algalish/SmartIssueTracker#24]

**Comment by CAGalvez** [comment]
Hello, and good day to you, Algalish.

I absolutely love your work with Smart Foundations and am happy to see you are planning to integrate MoarFactory walls and foundations.

Would you be willing to also include the PGlassS and maybe other items listed under the Factory category? And maybe the other categories like Doors, Stairs, Parts?  That would be so awesome if you could :-)

I've been working on my new factory with mostly the PGlassS and was hoping this would make your list of compatible items.

Again, thank you for the awesome work!

Carlos

**Comment by Algalish** [comment]
Hi Carlos!

I am glad that you like the mod!
Yes, I can support more stuff from MoarFactory. 
I plan to have an update for the mod tonight, so will probably include it in this update if it will not take a lot of time. Yep, thats the kind of service you get with Smart Foundation  ^^

@CAGalvez

**Comment by CAGalvez** [comment]
Wow!  That would be awesome!  Quick question for you, I am not in the experimental branch; I am on the Early Access 131382.  Will that make a difference with your planned update?

**Comment by Algalish** [comment]
@CAGalvez  Actually yes, the latest updates are only working on experimental. But its about a few days till the update hits the Early Access and once it does you will be able to use the mod right away. And since the version of the game will be 100% to the one that is currently in experimental you can already switch to experimental. All the popular mods are already updated to it

**Comment by CAGalvez** [comment]
Algalish, that is even better news!  I was not sure how much longer it would be for that.  I will go ahead and switch to the experimental branch.
Unless I missed it, I did not notice a link for donations on the SMM descriptions. Have you considered adding one?
-C

**Comment by Algalish** [comment]
@CAGalvez  I just created it recently so forgot to add it to the mod page: https://www.patreon.com/Algalish
With Patreon you don't have to make donations every month and can just make a one time donation by just cancelling the subscription right away. 
Thank you in advance!

**Comment by Algalish** [comment]
@CAGalvez  
I hate making false promises especially personal ones.
But here we are 2 weeks later and V.8 still does not have MoarFactory support.
I will try to do it in the next update that should be out in 3-4 days from now, but I am not 100% that will be able to do it. Anyway, just want to say that this issue is not forgotten by me.

**Comment by CAGalvez** [comment]
Hello @Algalish :-)
I was wondering if you were able to get the MOAR Factory support to work?  I am in the middle of a big project and am so used to using the standard foundations with your fantastic mod, but I have tried everything I can think of, including adding to my frequently used items at the bottom, and MOAR still does not work.

![Foundation95_Major_Project](https://user-images.githubusercontent.com/74146278/107417065-3557d080-6ae3-11eb-915f-b5dd1db5ab10.png)

**Comment by Algalish** [comment]
Since MoarFactory is not updated to U4 yet - I can't support it. Will wait and see how it plays out.
