### ISSUE TITLE
Repeatable Keypresses

### ISSUE THREAD

**Issue by alfons234** [Algalish/SmartIssueTracker#29]
First of all, it's a really great mod, even one of the best out there! I really appreciate it.
Unfortunately one can't customize the key bindings for the different actions which is a great pitty since not everyone has a keyboard with an english layout.
At least the arrow keys are a somewhat replacement for that, but could you please add repeated keystrokes to them? In a way that after pressing them for a second or so they repeat themselves. At the moment it feels like playing an arcade game from the 80ies with pressing the same key in rapid succesion over and over again.

Keep up the good work!

**Comment by Algalish** [comment]
@alfons234  arcade game from the 80ies ))) 
Sure man, will add this ability.

**Comment by Algalish** [comment]
wow, thats an old issue.
I will look into it soon butclosing the ussue here since all new features are now in discord ( https://discord.gg/mUKAb9Br ) and only bugs are left here.

**Comment by alfons234** [comment]
Thx and don't worry, I don't consider it longer as neccesary. With the introduction of the hold key it's easy to use the mouse wheel which is even better than repeated keypresses ;-)
