### ISSUE TITLE
Hold feature sometimes acts weirdly

### ISSUE THREAD

**Issue by ItsDaRa** [Algalish/SmartIssueTracker#32]
So as discussed on Discord, sometimes while aiming at different/far position the Hold feature disappear and display a 'invalid aim" error.
Please see here :
https://streamable.com/agjq8h

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
