### ISSUE TITLE
Disable/config Arrow keys

### ISSUE THREAD

**Issue by PeterSoder** [Algalish/SmartIssueTracker#38]
Since I'm lefthanded i use the arrow keys to move, would be nice if I could switch to using the wasd keys to size up the build.
As it is it makes it impossible to move when building/placing foundations.

**Comment by Algalish** [comment]
Hi @PeterSoder 
Changing keys should be available next week.

**Comment by PeterSoder** [comment]
Sad to see that it didn't make it into .8, unless I missed something

**Comment by Algalish** [comment]
@PeterSoder  I spent a lot of time working on the UI and only implemented major settings. I don't like keeping false promises but you can expect this to be done in the next update that will probably be out around Wednesday.

**Comment by PeterSoder** [comment]
No worries, I really like your mod and appreciate your work. 
Thanks for the update.

**Comment by JuanC74** [comment]
Hi,
I'm a leftie too. I found this MOD very useful. Maybe you can switch the key bindings pressing CAPS LOCKS. I only use the WASD keys while flying.

**Comment by Algalish** [comment]
@JuanC74 @PeterSoder 
In V.10 the option of change arrow keys to WSAD keys is added.
Let me know if its perfect now.

**Comment by PeterSoder** [comment]
It is perfect! 
Great work now I can enjoy it even more!
