### ISSUE TITLE
(Experimental) Builds duplicate foundations when elevating, stepping up/down does nothing

### ISSUE THREAD

**Issue by FerosNS** [Algalish/SmartIssueTracker#39]
Holding **E** and using the scroll wheel to change elevation will build two walls/foundations. One will be where you're aiming, the other will be placed at the elevation you're trying to place it. 

Holding **U** and using the scroll wheel does absolutely nothing noticeable.

Since multiple mods were installed, I removed all but Smart Foundations to make sure there were no other conflicts first.

**Comment by Algalish** [comment]
Hi @FerosNS !
1) Yes, this is actually a known problem. Will try to fix it in the upcoming updates. But it may not be a bug 100% since it helps you look where the original foundation is placed to understand where the original location of the foundation is. So maybe it is a good idea to show it but just not build it.

2) Will check it later today.

**Comment by Algalish** [comment]
@FerosNS 

for U to work you have to have a foundation with more then one element. it works like that: 
![Screenshot_38](https://user-images.githubusercontent.com/1682176/98690588-25aedb80-237e-11eb-94c7-27c6385682d6.png)

**Comment by FerosNS** [comment]
Ah that's where I went wrong with the step function! Didn't realize it did it with multiple foundations.

The major reason why I figured the duplicate placing with elevations was an issue is that trying to elevate over an obstacle (or in my case under while I was trying to build walls) would prevent me from placing a piece at the desired elevation as it would be considered encroaching on something already existing.

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
