### ISSUE TITLE
curved foundations?

### ISSUE THREAD

**Issue by TRPB** [Algalish/SmartIssueTracker#41]
Firstly thanks for this, it makes the game much more enjoyable. Would it be possible to also enable this for the curved foundations you can buy in the shop?

**Comment by Algalish** [comment]
@TRPB  Thank you!
Yep, will add them for you in the next update

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
