### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by CoolHandDevil505** [Algalish/SmartIssueTracker#45]
Hi, and thank you for this great mod, saving me from index arthritis!

I have a crash when exiting the game, with only your mod installed… No mod, no crash like Bob sang ;-)

[SF_crashonexit.txt](https://github.com/Algalish/SmartFoundationsPublic/files/5570153/SF_crashonexit.txt)

Have a great day!

**Comment by Algalish** [comment]
@CoolHandDevil505  sorry for not replying right away. some people say that this crash is normal in general and is not related to a mod. but I will definitely have a deeper look at that

**Comment by CoolHandDevil505** [comment]
Ok thanks!

**Comment by imtheman0313** [comment]
Can confirm, crash on exit.  This is with Smart! mod only, with Smart! and ExoSuit, with Smart! and Nuclear Waste Recycle.  With ExoSuit alone, no crash.  Nuclear Waste Recycle alone, no crash.  ExoSuit and Nuclear Waste Recycle, no crash.  As soon as I add Smart! to it, crash on exit.  This does not seem to affect gameplay (except the obvious using full inventory to build large areas lagging things, Unreal really doesn't like that)  If you like, I can save the crash report and paste it here next time it happens.

**Comment by imtheman0313** [comment]
Also, I forgot to mention.  I am using the Mod Manager for mod installs, if that makes any difference.  I have also tried a couple different launch and end game tactics, all resulting in the crash box appearing.

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
