### ISSUE TITLE
foundation z-axes build direction missed

### ISSUE THREAD

**Issue by sidoitsu48** [Algalish/SmartIssueTracker#49]
Thanks for your mod. 

Building in x, y direction with your mod is really cool but I miss switching plane to build in x, z or y, z direction for fundations. Building a pillar is currently not possible and I do not mean your elevate function.

**Comment by Algalish** [comment]
@sidoitsu48  you mean a pillar of foundations right? because you have also smart! pillars 

I will add Z in next updates 100%. probably shift+alt together.

**Comment by Algalish** [comment]
@sidoitsu48 this is done in V.11
