### ISSUE TITLE
Add support for fuel generator and the new packager building

### ISSUE THREAD

**Issue by swent** [Algalish/SmartIssueTracker#50]
First of, thanks so much for this great mod, I guess its one of the only reasons I still keep playing since otherwise building huge factories would be too time consuming.

I would appreciate support for fuel generator and packagers.

And while we're at it, maybe even water extractors (but I don't know if thats gonna be a problem since individual placment in deep water is required).

Thanks again!

**Comment by Algalish** [comment]
@swent  Thx for your kind words.
Yea, I totally forgot about the fuel generator. Although packager is not in the video - it should be supported already.
As per water extractors : it would be marvelous to build them too but I was not able to implement that in this update. Will definetly do it later.

**Comment by swent** [comment]
@Algalish is there a way to directly support you via paypal instead of patreon?

**Comment by Algalish** [comment]
@swent  sadly in my country it is not easy to setup a "paypal donation link" due to some regulations. but you can send me a direct paypal transfer to my email me@algalish.ru if that works for you. thank you!

**Comment by Algalish** [comment]
@swent fuel generator added in V.12
packager was there for a long time
