### ISSUE TITLE
Suggestion: Arc/Circle construction

### ISSUE THREAD

**Issue by therodet** [Algalish/SmartIssueTracker#51]
Would love to see an option to place foundations and walls in a curved/arced pattern, possibly with the option to toggle whether the inside or the outside edges of the patterned objects stay connected (Outside would result in overlapping, inside would not). A google image search of "satisfactory platform circle" will show what I mean if not clear. Would be great for road and railway paths, or just really cool buildings.

**Comment by Algalish** [comment]
This is a new feature.  New features are now in discord ( https://discord.gg/mUKAb9Br ) and only bugs are left here.
