### ISSUE TITLE
Suspeted crash during auto save

### ISSUE THREAD

**Issue by vinnyviking** [Algalish/SmartIssueTracker#52]
Hi,

I am building long line of singe wide foundations (100*1). Most of the time this works OK but when I have this line selected and an autosave occurs the game xcrahces.
[FactoryGame - Copy.log](https://github.com/Algalish/SmartIssueTracker/files/5579947/FactoryGame.-.Copy.log)

**Comment by Algalish** [comment]
@vinnyviking  sorry, forgot to reply right away.

will investigate this but not sure if there will be a quick fix. to many factors that can cause this(

**Comment by vinnyviking** [comment]
No problem,

As there is a workaround (do not use that many tiles) there is no hurry in fixing but I thought you should know this.

BTW I really love your mod. Just build a larger factory using it.

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
