### ISSUE TITLE
Buidling construction not working for multiplayer client

### ISSUE THREAD

**Issue by jmigual** [Algalish/SmartIssueTracker#53]
Hi, many thanks for this mod, it is amazing.

Here's an issue that we found while playing on multiplayer:

If the client tries building multiple buildings like constructor, assembler, manufacturer or smelter, the game only ends up building the one that was initially meant to be build and not all the ones.

**Comment by Algalish** [comment]
@jmigual  oh man, I completely forgot to add the multiplayer compatibility for smart buildings.
originally it took more then 60 hours to make multiplayer work (I know, right?)
but adding new buildings to multiplayer is like a few lines of code now.

**Comment by jmigual** [comment]
Thanks! Nice to know that you prepared in advance so adding multiplayer would be easier

**Comment by Shad0wlife** [comment]
As already informed on discord, here the additional info that multiplayer seems to have broken (client crashes on join) with v0.9.
Thanks for your effort.

**Comment by Algalish** [comment]
@jmigual @Shad0wlife 
It is fixed now. let me know if you'll have any other issues
