### ISSUE TITLE
[Request] FoundationIndustries Compatibility

### ISSUE THREAD

**Issue by Shad0wlife** [Algalish/SmartIssueTracker#62]
Hey, since you seem to add compatibility with popular foundation mods in here, would you mind taking a look into [FoundationIndustries](https://ficsit.app/mod/FDbifQ2WdwJaQB)? If it's not already supported that would be great!

Thanks for this amazing mod!

**Comment by Algalish** [comment]
Once it is supported in U4 I will get back to that
