### ISSUE TITLE
Min Distance between stackable poles could be smaller

### ISSUE THREAD

**Issue by Snucker** [Algalish/SmartIssueTracker#64]
![image](https://user-images.githubusercontent.com/2848723/100306808-45472600-2f72-11eb-9277-c17800f0d6af.png)

**Comment by BratrilliantG7** [comment]
Yes, please. Since we can now add spacing between buildings ourselves, making the poles directly next to each other by default would be wonderful.

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
