### ISSUE TITLE
Spacing between smelters not always equal [bug]

### ISSUE THREAD

**Issue by DrLeot** [Algalish/SmartIssueTracker#65]
Just found out while trying the mod that setting the spacing of the smelters to another value than the default one (with "p" key), the spacing isn't always equal. As more items I want to place, the smaller the space gets. 

Maybe some float-rounding bug?

I haven't checked other buildings yet.

**Comment by Algalish** [comment]
@DrLeot  Thx for finding that. I will look into that asap.
But can you confirm first if this still present in V.10 of the mod? And maybe with some screenshots. Thx!

**Comment by DrLeot** [comment]
@Algalish All right thanks for replying. I have installed V.10 and the error still occurs. While being in creative mode, i tried out several building and found out, that only the smelters are not aligned. I tried to center the smelters in the middle of a foundation eq. spacing 2x0.5foundation in between. After having 18 smelters by each side, the last smelter is around only 1x0.5foundations away from the last on. Hope this give you some ideas what the issue is. Image 2 is the beginning of the row and image 3 are the last few smelters in the row

<img width="633" alt="2020-12-01 12_09_27-Satisfactory Mod Manager" src="https://user-images.githubusercontent.com/10046378/100735185-16e1a480-33d1-11eb-9124-ac03a8278192.png">

<img width="1220" alt="2020-12-01 12_28_59-Satisfactory" src="https://user-images.githubusercontent.com/10046378/100735256-38db2700-33d1-11eb-99dd-c822d2821e28.png">

<img width="1159" alt="2020-12-01 12_29_33-Satisfactory" src="https://user-images.githubusercontent.com/10046378/100735267-3b3d8100-33d1-11eb-8168-992706ab5b1c.png">

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
