### ISSUE TITLE
Chat command /smart doesn't work

### ISSUE THREAD

**Issue by InsomniacSoftware** [Algalish/SmartIssueTracker#66]
I just updated to v10 and tried the /smart command in chat but it doesn't work.  It shows "System: Unknown command"

**Comment by Algalish** [comment]
@InsomniacSoftware  
Hey there!
Because there was no easy way to make the chat command work in multiplayer, I decided to go the other way and now you can open mod settings by pressing M while building something with Smart!  I asked several people and they liked the idea, hope you like it too,
