### ISSUE TITLE
Option Menu

### ISSUE THREAD

**Issue by alfons234** [Algalish/SmartIssueTracker#67]
Hey man, I really like your mod, your many updates, the work you put in.
The simple press of the button 'M' for accessing the menu is a really improvement.
Can you please add your instructions too to your options menu? Like:
"Hold 'U' and scroll your mouse to step up or down
  Hold 'T' and scroll your mouse to twirl(offset) left or right. ......"
Since folks don't always build and use your mod all the time it would be really helpfull to get a quick memory refresh without leaving the game and having to look elsewhere.

But what really annoys me is the fact that your option menu opens after every start of satisfactory automatically. In my humble opinion it is another unneccesary splash screen like so many others in windows and other programs. The Smart! options are only needed when building and then only until one has found his optimal settings.
As a matter of fact it scares me quite a bit, since you made a precedence with your splash screen. I played satisfactory for about 50 hours vanilla, but I am using now over a dozen mods. It is quite a horrifying thought if the other modders would follow your example and include such a splash screen as well and every player using mods had to close a splash screen for every mod he uses just to load the save file, that is definitely a hugh downer.
So I humbly ask you to find a less annoying way to satisfy your ego, since in my opinion you are already the king of the modders for satisfactory ;-)

**Comment by Algalish** [comment]
@alfons234  I am so sorry to hear that you got my welcome screen EVERY time you open that game.
My ego is not invloved here, this is just a bug.
This screen is supposed to open ONCE when you update the mod to a new version. That's it.
I think you are the first to report this. 
To understand what is going on can I ask that you send your "SmartFoundations.cfg" file from the "C:\Program Files (x86)\Steam\steamapps\common\Satisfactory\configs" or other folder where you game is located.

My appologies for the late reply, been very sick the whole week and still not 100% recovered.

I will add info with the build keys in the next updates. Of course, this could be very usefull.

**Comment by Algalish** [comment]
@alfons234  I would not think that anyone in their right mind would ever want to open a splash screen every time user loads the game. Thats just ... horrible.

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
