### ISSUE TITLE
Build Info Location [Suggestion]

### ISSUE THREAD

**Issue by BratrilliantG7** [Algalish/SmartIssueTracker#69]
Being able to choose where to put the build info would be a nice option. However I have a couple suggestions:

1. The old left hand location would clip behind the "Early Access" build text when you did more than one extra action, like elevation and step. So perhaps move it down slightly.

2. The new right hand location goes behind the milestone box, which 90% of players always have up. Perhaps either move it below the Milestones or to the left of it.

3. Maybe an option for the top middle, right below the compass. If you could make the text box move so it's always centered as the build info changes, that would be great, but if that's a technical limit at the moment, then just a stationary spot would be fine, even if it will look off-center sometimes.

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
