### ISSUE TITLE
Build Info doesn't display if you only change an extra option [Bug]

### ISSUE THREAD

**Issue by BratrilliantG7** [Algalish/SmartIssueTracker#70]
For most of the options, this doesn't matter since they rely on having more than a 1x1 for any of them to visibly work. However I wrote this because the same applies to Elevation. Sometimes I just want to build a single foundation way up in the air, but I have no idea how far it is until I use shift or alt to change one of the build directions. I can revert it back to a 1x1 then the info will display my elevation just fine, but it's a minor annoyance to have to do that to begin with, you know?

**Comment by Algalish** [comment]
@BratrilliantG7  Good catch! I will definitely fix it in the next update. So as long as you do ANY changes- this will be shown, not just when the size is going to be more then 1x1

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
