### ISSUE TITLE
Coordinates of placed foundations are getting 'off' when placing larger quantities of foundations.

### ISSUE THREAD

**Issue by sand3r** [Algalish/SmartIssueTracker#72]
Recently I started a new playthrough, because the coordinates from my foundations got 'off', resulting in foundations not connecting properly to each other (before using Smart!):

![Foundations misalign](https://preview.redd.it/k6ejv6bawdz51.png?width=2560&format=png&auto=webp&s=933a2a8466b3bd1f615e31f69d4fde48db7fd062)

I discovered via https://satisfactory-calculator.com/en/interactive-map that the coordinates of foundations had many decimals behind them ending up in a misaligned (well... I tried to build everything on one 'large' grid) factory.

**In my new playthrough I started to experiment with Smart.**
After placing large sections of foundations with Smart, I noticed also that the decimals on the coordinates were appearing again. Is it possible to prevent this from happening? I'd really like to keep my factory on a clean grid this time :)

![Coords in foundation position, after placing 10x4](https://i.ibb.co/dtmqkbH/Screenshot-2020-12-01-232514.png)

**Comment by Algalish** [comment]
@sand3r  Good catch! I am not feeling well today but will get back to you with some questions within a few days. We will get it right.

**Comment by sand3r** [comment]
All the best and take care!

**Comment by Algalish** [comment]
@sand3r  so you are saying that even in the vanilla game there is a problem like that?
I will of course look into that more but if this would have been a Smart! bug - that would be easy, but if thats the Satisfactory bug... well, I am afraid that I am kind of limited on my options here.

**Comment by sand3r** [comment]
I had the problem in my previous playthrough, but that happened because I started off wrong with my first foundation. I only found out very late in the game when my foundations after a large 'loopback' did not align anymore. It turnes out the game saves positions on x, y, z with max. 9 decimals but rotations only 3. 

So yes, the game can bite you if you start of wrong.

But, normally in vanilla it does not happen. I have seen rare occurences though, but now I have laid out my entire base (~ 10k foundations) and I'm only aware of 1 instance in my current playthrough where it happened 'vanilla'. That was with laying out steep 8x4m double foundations but otherwise it never happens (you can have my save if you like of course).

However, using Smart!, when I lay out for instance 30x6 chances are pretty high that it is going to happen unfortunately. So; vanilla it is possible in really rare occurences.

**Comment by Greedo-fr** [comment]
That is a known issue in Satisfactory, linked with how computers store floating point values. 
Workaround from subreddit was is to have foundations aligned NSEW.
I'm not sure Smart mod will be able to correct this. Good luck

**Comment by sand3r** [comment]
Hi,

That's correct, when it is not placed 100% NSEW, you will definitely run
into this issue.

However as I tried to describe, using this mod, 'misalignments' will happen
anyway, even if the rest of your base is 100% aligned NSEW (checked with
the Satisfactory Calculator website). Coords are perfectly on the .0 mark
when placed manually.

Thanks for the reply anyway :)

**Comment by catonthekbd** [comment]
Would it be possible to have some special key to force foundation positions x,y to be multiple of 8, z multiple of 4, and rotation 0 ? (when dropping a foundation  that is not snapping to any other)  - Making it easier to build factory units in different places that still line up with each other

Or would we still be bitten by SF's floating point limits?

(strong suspision it is not possible ...)

**Comment by Algalish** [comment]
@sand3r 

Yes, this is a floating point precision issue.
I did some investigation and I don't think that there is someting that I can do that will fix this since Sf itself builds foundations like that.

@catonthekbd 
The idea of forcing rotation to 0 and "sticking" foundation to only round numbers (there is even non need to make them 8 or 4 , just ignoring the .0001 stuff should help)

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
