### ISSUE TITLE
[Suggestion] Foundation vertical stacking

### ISSUE THREAD

**Issue by headcase0570** [Algalish/SmartIssueTracker#74]
When placing foundations I'd like the ability to stack vertically/Z axis. It'd make creating 3x3x20 or 6x6x40 pillars a lot easier and faster!

**Comment by BratrilliantG7** [comment]
This would be a nice addition. Probably use a new key like the other extra options.

**Comment by Algalish** [comment]
@BratrilliantG7 @headcase0570 
Done in V.11 
Enjoy!

**Comment by headcase0570** [comment]
Thank you!
[https://i.imgur.com/HxOT5.png](url)
