### ISSUE TITLE
Allow negative P or provide a way to build up

### ISSUE THREAD

**Issue by aalexgabi** [Algalish/SmartIssueTracker#75]
I want to make a tower. Is there a way to stack foundations on top of each other?

I tried using shift and then the number of foundations and use p to make them stand one on top of the other.
Seems that p cannot be negative so it's not possible to do what I wanted but it would be very useful it it could.

Another way would be to implement a feature to build up as for shift and alt.

**Comment by Algalish** [comment]
Right now you can’t. It is planned and will be available soon. However I am
currently sick and not be able to work on the mod for the next week.

**Comment by Algalish** [comment]
@aalexgabi  Did that in V.11
Is this exactly what you wanted?

**Comment by aalexgabi** [comment]
@Algalish Woow! That was quick! Thank you very much. I just made a donation on Patreon!
