### ISSUE TITLE
Game not starting with mod enabled

### ISSUE THREAD

**Issue by Merkury90** [Algalish/SmartIssueTracker#78]
Hello.

For quite some time now - Ibelieve 2 last versions (10 and 11) I'm unable to launch a game with Smart Mod enabled.
I'm getting error with SML crashing and failing to load module. Below screenshot with the error msg.

Is it mod related, Mod Manager related or maybe my game is corrupt?
Thanks in advance for any help.

Best regards!
![screen](https://user-images.githubusercontent.com/75625095/101362631-a50dcd00-38a0-11eb-80d4-e697d9e42b29.PNG)

**Comment by Algalish** [comment]
@Merkury90  There is something wrong with the SML. Guys at discord recommended you to clear cache of SML like that.
Let me know if that helped you.
Or you could delete the whole .cache folder manually
![unknown](https://user-images.githubusercontent.com/1682176/101386860-c685ad80-38ce-11eb-8118-bf7185711451.png)

**Comment by Merkury90** [comment]
@Algalish
I used this option to clear cache - it didn't help.
I also tried to remove the cache folder from error msg - didn't help either.

Is there any log file I can provide to help track this issue?
