### ISSUE TITLE
Add Smart! Color Gun

### ISSUE THREAD

**Issue by EvilYodeler** [Algalish/SmartIssueTracker#79]
The ability to select multiple items for painting would be amazing. I have huge buildings in my world and to be able to select large sections of walls for recoloring would be a great asset.
 Thank you for your time!

**Comment by Algalish** [comment]
Hey, @EvilYodeler 
I thought about adding a new feature with "C" button that when holding it will mouse scroll(or arrow keys) through different color pressets. do you think that it will work for your case? But I would have to take the color cartridges from the user inventory, I still want Smart! to not create things from nothing. Or maybe add an option in settings to take or not take color cartridges for that.

**Comment by EvilYodeler** [comment]
I think I am speaking more to the idea of painting multiple selected buildings at once with whatever color is set in the Color Gun. Using cartridges from your inventory would be great. The option to use/not use cartridges would be a "nice to have" config...  :)

**Comment by Algalish** [comment]
This is a new feature.  New features are now in discord ( https://discord.gg/mUKAb9Br ) and only bugs are left here.
