### ISSUE TITLE
Smart constructor with "P" spacing is not aligning [bug]

### ISSUE THREAD

**Issue by jay061996** [Algalish/SmartIssueTracker#80]
(tested with V.11)
In the image, the built constructors and splitters were hand placed onto foundation and align together, however the smart holograms when being spaced do not align with the splitters.
![2020-12-08_1-1](https://user-images.githubusercontent.com/1531040/101551199-aa414980-397e-11eb-9d54-2b9d68818157.png)

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
