### ISSUE TITLE
Cycle through modes instead of held [enhancement]

### ISSUE THREAD

**Issue by jay061996** [Algalish/SmartIssueTracker#81]
Currently the mod has keys U, T, E, and P which are held to do up/down stepping(U), left/right stepping(T), up/down offset(E), and combined foward/backward/left/right spacing(P).
These lack foward/backward stepping, foward/backward and left/right offset, up/down spacing, and uncombined foward/backward/left/right spacing.

My suggestion is to only use T to toggle modes(or maybe open a radial?) between default, stepping, offset, and spacing, which will then use shift for forward/backward, alt for left/right, and alt+shift for up/down across all modes. Will likely require an on screen indication of the current mode to be added attached to the current overlay.

**Comment by Algalish** [comment]
@jay061996  I really like that idea. Can you tell me your discord name so we could discuss this more?

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
