### ISSUE TITLE
Add Smart! power poles

### ISSUE THREAD

**Issue by Algalish** [Algalish/SmartIssueTracker#82]

**Comment by LooSik** [comment]
Would be great to have this working for wall outlets as well.

**Comment by DesktopMan** [comment]
Power poles and wall outlets would be great.

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
