### ISSUE TITLE
Can it be installed and disabled?

### ISSUE THREAD

**Issue by jbarradale** [Algalish/SmartIssueTracker#83]
I play Multiplayer with someone that uses the Smart Mod, but I do not care for it. Can I have it installed, so that it will allow me to play with my friends, but disabled. It interferes with my key assignments. I use the arrow keys to move, so when I am building with this mod I am unable to move around. I have to exit build mode and then go back each time I build different objects or in different places. I like the idea of it. I do not usually use mods to make building faster. Thank you.

**Comment by Algalish** [comment]
Hey @jbarradale  I plan to add this option within the next few weeks. So you will be able to just go to settings of the mod and disable it. But right now you can already disable the arrows when building.

**Comment by Algalish** [comment]
@jbarradale  you can now disable the arrow keys by going to mod settings and set "alternative ontrols" to "Disabled"

**Comment by jbarradale** [comment]
Thank you for your reply. I did some reading and found that I could change the option to use the WASD keys. So, I can now use it without problems. Thank you very much for a kool addition to our Satisfactory experience in both single player and Multiplayer with UnkemptGamer every week.
 

jb

 
 

Sent: Friday, December 18, 2020 at 1:10 PM
