### ISSUE TITLE
x3-Road Highway-Fence Left (Ramped) not working as expected

### ISSUE THREAD

**Issue by pedroivorbgrodrigues** [Algalish/SmartIssueTracker#84]
As you can see in the image the left side doesnt work as the right side. (Yes, Im placing it reversed, but the behaviour is what is broke).
![image](https://user-images.githubusercontent.com/293789/102682167-39800580-41a6-11eb-9ed0-4a39e0b1e229.png)
![image](https://user-images.githubusercontent.com/293789/102682185-6207ff80-41a6-11eb-9c7d-2518908ba910.png)

**Comment by Algalish** [comment]
@pedroivorbgrodrigues 
I know that it's been more then 2 months since you found this bug.
But I fixed it and if you can confirm that this is working fine - you can close this issue.
I will release V.16 soon or you can already check it with this test version 
https://we.tl/t-eR376t81S9

**Comment by pedroivorbgrodrigues** [comment]
Thank you for your work! I stopped playing but I'm happy we sorted this out. =]
