### ISSUE TITLE
arrow keys for moving

### ISSUE THREAD

**Issue by Baby1B** [Algalish/SmartIssueTracker#87]
i am one of those weird people that use my arrow keys to move in game.  I want to use this mod over the pak utility mod but cant cause my weird issue.  is there a way to disable the arrow keys or re key bind them?  I do believe I have seen this asked here before and thought it was in the works but that was about a month ago.  any reply would be appreciated thank you!!!!

**Comment by Algalish** [comment]
Hey @Baby1B .
Its already done in the last update. Just open settings and select “disabled” in alternative input. And you are good to go!

**Comment by Baby1B** [comment]
o dang sweeeeeeet thank you every time i read the mod i just see the arrows as alternate lol thank you sooo much!
