### ISSUE TITLE
Update Distance Placement(P)

### ISSUE THREAD

**Issue by FaTaL6266** [Algalish/SmartIssueTracker#90]
This idea came to me when messing around with water extractors. I would like to be able to modify the spaces between building in each direction separately. By this, I mean that if I have a set of 2x5 buildings, in this case, water extractors specifically, I'd like the rows of 5 to be right next to each other, but I want the distance between rows to be large enough to fit foundations between them. As it is now, using P+Scroll will change the spacing between both the rows and columns of the buildings.

I've included a very rudimentary illustration of what I mean where each X indicates a building.

![Untitled-1](https://user-images.githubusercontent.com/60488538/103183951-75405c80-4883-11eb-9b0b-71c899a9ef7b.png)

**Comment by Algalish** [comment]
Hey @FaTaL6266  
Yea, I already thought about that and there is an active ticket for that.  It actually should work for 3rd dimension too.
But what will help is the idea of control for that logic: like what buttons are best for using that.
Maybe holding P will turn on all 3 dimensions , pressing P will toggle different directions?  Like  X, Y, Z, ALL ?

**Comment by FaTaL6266** [comment]
I think something along those lines could work, but I would think that you would want to make it standard across all machines. Perhaps it can be done without having to press P at all. Would it be possible to just hold X, Y, or Z and use the scroll wheel to adjust them each individually?

**Comment by rdelassus** [comment]
Came here to see if it was already discussed! 
It's frustrating that I can't properly align on foundations on X axis when Y axis is aligned and vice versa.
I would have instinctively separated that in two keys, one for each axis. I see no reason for a toggle, since we are not toogling X and Y expansions, they are two different keys (alt and shift)

**Comment by Algalish** [comment]
@rdelassus  @FaTaL6266 
Thought of a solution recently that will probably fit everyone.

if you press P : you are in a spacing mode: so  shift/alt/shift+alt will alter spacing and not the size of the buildings.
press P again and you are back to normal mode.

oh and if you changed some values with a mouse wheel while holding P then X and Y dimensions will be affected, like now. and when you put your finger from P - you are back in normal mode, no need to press it twice. Or will that only complicates things?

let me know if you guys think of something else that is better.

**Comment by rdelassus** [comment]
First solution looks perfect. I think there aren't many use cases for the
second feature, and it will be easier to make mistakes (moving along both
directions when you just wanted to change the toggle, but started mouse
wheeling too early).

**Comment by Algalish** [comment]
This will be done soon but new features are now in discord ( https://discord.gg/mUKAb9Br ) and only bugs are left here.
