### ISSUE TITLE
[Suggestion] Conveyor lift height displayed on new UI

### ISSUE THREAD

**Issue by RandomUsername27** [Algalish/SmartIssueTracker#91]
With the new rebranding, and extension of the mod's scope to things other than foundations, and the addition of the new UI displaying the dimensions, elevation, twirl, and so on of SMART stuff being placed, I had the idea, that conveyor lifts (and maybe ladders) could have their current extension (height) shown. 
For now we have to rely on dumb ways like counting manually, or looking at the hologram and trying to figure it out based on it's textrure, however with SMART our lives could be made so easy that you could even cover most of the screen and we'd still be able to build perfectly.

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
