### ISSUE TITLE
Game Crash with Smart Mod

### ISSUE THREAD

**Issue by Gainer69** [Algalish/SmartIssueTracker#94]
I have had this happen several times, while I am building a platform and holding down ALT and accidently hit right click the game will crash suddenly.  Does this happen to anyone else?  If no, I can provide information on what other mods I have installed but since I am in the middle of a Smart Mod function I expect it is related.

**Comment by Algalish** [comment]
@Gainer69  I will look into that. Not a common scenario so no reports of that so far

**Comment by TheElementalOfDestruction** [comment]
I occasionally get similar issues with smart if I am doing a build of some sort, am holding one of the modifier keys, and accidentally bump right click. Does not appear to happen every time, as attempting to exactly repeat the problem has not produced a crash.

When the crash came up, I saw mention of "smartfoundation" in the traceback, and it had something to do with the holograms and a nullptr access violation. I can send you crash files or whatever you need so you can take a look.

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
