### ISSUE TITLE
Is there a point to -1?

### ISSUE THREAD

**Issue by Birdulon** [Algalish/SmartIssueTracker#97]
Currently, decrementing any axis from 1 makes it -1. As far as I can tell it doesn't seem to be meaningfully different from (+)1, and it adds another keypress/mousewheel click to get from 1 to -2.
It would be nice to be able to go from 1x1 to e.g. -2x-2 with only 2 presses instead of 4.

Great mod btw, the quality of life improvement is tremendous!

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
