### ISSUE TITLE
[Suggestion] You should add Moar factory support

### ISSUE THREAD

**Issue by Einstein725** [Algalish/SmartIssueTracker#98]

**Comment by Thunde33** [comment]
Yes pls add support for this great mod. It has the best glass walls.

**Comment by CAGalvez** [comment]
Pretty please with sugar and a cherry on top!  I use so many of their foundations and walls, and it is a pain now that I have gotten used to using your mod for the other regular foundations.  You have spoiled all of us.
I am in the middle of a major storage site build and use the Foundation95, as it has a tiny flicker when overlapped compared to the regular ones.
![Foundation95_Major_Project](https://user-images.githubusercontent.com/74146278/106167860-a7333000-615b-11eb-9bad-115554fe9f29.png)

**Comment by Algalish** [comment]
@CAGalvez 
@Einstein725 
@Thunde33 

It is possible that Moar factory will not be updated for Update 4 of the game.
So it will be either completely gone or someone will re-create the mod and make it a new mod.
Or the mod author will support it for update 4.

So, after anything of the above happens - I will add support to Smart! right away.

**Comment by Algalish** [comment]
Moar is not working in U4. Once it does - I will get back to that task
