### ISSUE TITLE
Splitters/Mergers incorrect offset when building vertical

### ISSUE THREAD

**Issue by pcman312** [Algalish/SmartIssueTracker#99]
When placing splitters/mergers with shift+alt to place several vertically, the splitters/mergers do not have the same height compared with placing two normally.

See screenshot below. The left splitters were placed by hand while the right splitters were placed with Smart (shift + alt). The stackable conveyor pole is an unmodded pole also showing the incorrect height.
![20210121225700_1](https://user-images.githubusercontent.com/72365/105452886-5b085d00-5c3c-11eb-84f8-c2fbae5e6772.jpg)

**Comment by Algalish** [comment]
https://we.tl/t-L9hZzGGebh

Hey @pcman312 

Can you confirm that in this version everything works fine?

**Comment by pcman312** [comment]
That looks correct to me. Thanks a bunch!

**Comment by Algalish** [comment]
@pcman312  Great, you are welcome. The fix will be added to V.15
